### ISSUE TITLE
uptasticsearch broken on CRAN

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/uptasticsearch#135]
Got one of those "your package is suddenly broken on CRAN fix it ASAP or we're taking it down" emails from Kurt Hornik last night.

You can see the results here: https://cran.r-project.org/web/checks/check_results_uptasticsearch.html

The relevant bit of the log is:

```
 > testthat::test_check('uptasticsearch')
     ── 1. Error: (unknown) (@test-parse_date_time.R#180) ──────────────────────────
     there is no connection 3
     1: closeAllConnections() at testthat/test-parse_date_time.R:180
     2: close(getConnection(set[i]))
     3: getConnection(set[i])
```

We haven't pushed a new release June 2018, so that means that either they added new environments they test in or there was a breaking change in `closeAllConnections()`.

I think we can just remove `closeAllConnections()` calls from our tests.

**Comment by austin3dickey** [comment]
agreed, we didn't need those
