### ISSUE TITLE
Remove "old = names(DT)" from calls to data.table::setnames

### ISSUE THREAD

**Issue by austin3dickey** [UptakeOpenSource/uptasticsearch#29]
A few times in our codebase, we have 

`data.table::setnames(someDT, old = names(someDT), new = new_names)`

This is actually _less_ safe than the following call with unnamed arguments:

`data.table::setnames(someDT, new_names)`

because the former will break when `someDT` has duplicate column names. It's not this package's job to break if there are duplicate names in a user's data.

**Comment by kszela24** [comment]
Resolved with PR #46
