### ISSUE TITLE
Should be using httr::RETRY instead of httr::POST

### ISSUE THREAD

**Issue by austin3dickey** [UptakeOpenSource/uptasticsearch#37]
https://github.com/UptakeOpenSource/uptasticsearch/blob/cfe11a50f9715311909372db102e85eb080ebd65/r-pkg/R/elasticsearch_parsers.R#L1107

Right now if a single request fails, so does `es_search`

**Comment by jameslamb** [comment]
thanks for getting this one @erichall87
