### ISSUE TITLE
es_search breaks with duplicate fields

### ISSUE THREAD

**Issue by kzenstratus** [UptakeOpenSource/uptasticsearch#54]
```
Error in data.table::setnames(batchDT, old = names(batchDT), new = gsub("_source\\.",  : 
  Some duplicates exist in 'old': _source.details.issueName
```

https://github.com/UptakeOpenSource/uptasticsearch/blob/b3cffef4401ce85722277839d7267a5bd7206de0/R/elasticsearch_parsers.R#L501

If an elastic search result populates duplicate fields, this es_search will break here.

**Comment by austin3dickey** [comment]
This was fixed in #46. You can use `devtools::install_github("UptakeOpenSource/uptasticsearch")` to install the latest version.
