### ISSUE TITLE
es_search should reject NULL passed to index

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/uptasticsearch#57]
I accidentally did this tonight, and got unexpected behavior. With a `NULL` for index, your URL will look like `http://mycluster.whatever:9200//_search`, which is totally valid for Elasticsearch and means "search all indexes".

I propose that the case where you are explicitly passing a NULL is almost CERTAINLY a mistake and we should err on the side of caution and break when that happens. Searching over all indexes is a valid use case (e.g. for cases where you have data with the same mapping stored in different indexes for different time periods), but we should only support it by explicitly passing `_all`.

Thoughts @ngparas @austin3dickey @mfrasco ?

**Comment by austin3dickey** [comment]
Sounds good, though we should clarify that in the docs too.

**Comment by jameslamb** [comment]
@mfrasco I'm not a `.ValidateAndFormatIndex` is right for _this_ particular issue. Not passing an index is "valid".

I also want to avoid validating queries because the query DSL changes radically from major ES version to major ES version. We've explicitly tried to keep the scope of this project to the execution or requests and parsing of results.

My concern isn't explicitly that the query will take too long, since the query-all-indices use case should definitely be something we support. My thinking is that allowing `NULL` means that you can find yourself in that world _silently_. Forcing people to use `"_all"` is safer.

FWIW I hit this when I was trying to subset into the output from `get_fields()` then pipe the result of that to `es_host`. I wrote a bad subset condition which silently evaluated to `NULL`, and then noticed in the log that `es_search` was trying to pull WAY more data than I expected.

**Comment by mfrasco** [comment]
Those are great points. Thanks for explaining.
