### ISSUE TITLE
Weird error when Parallel::detectCores() returns NA

### ISSUE THREAD

**Issue by drkarthi** [UptakeOpenSource/uptasticsearch#79]
Error message for reference: `Error in if (!is.integerish(x)) return(FALSE) : missing value where TRUE/FALSE needed`.

**Comment by drkarthi** [comment]
That sounds like a good way to handle it. I will make a PR for it!

**Comment by jameslamb** [comment]
Thank you @drkarthi ! I'm going to assign the issue to you.

No rush!

**Comment by jameslamb** [comment]
@drkarthi are you still planning to come back to this?

**Comment by drkarthi** [comment]
@jameslamb Thanks for the check-in. Can you take a look at the PR and let me know your thoughts?
